### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Silex**
I am not completely sure this is correct, feel free to close if it isn't :wink:

### CODE REVIEW

**Comment by tarsius** [comment]
Since you have to implement the functions that show and set the variable yourself you can indeed set any variable, or do something completely. That wasn't the intention initially, so this is not a typo just information that isn't quite accurate anymore. Please adjust the commit message accordingly.

**Comment by Silex** [comment]
Done.

**Comment by tarsius** [comment]
Merged with amendments in 1f12baa38cc89a06eba14f2e7797ced1937a8f68.

**Comment by Silex** [comment]
:+1:

**Pull request closed without merging**
